// import React from "react";
import LLARS0 from "../assets/llars0.jpg";
import LLARS1 from "../assets/llars1.jpg";
import LLARS2 from "../assets/llars2.jpg";
import LLARS3 from "../assets/llars3.jpg";
import LLARS4 from "../assets/llars4.jpg";
import LLARS5 from "../assets/llars5.jpg";
import LLARS6 from "../assets/llars6.jpg";
// import LLARS7 from "../assets/llars7.jpg";
import SF0 from "../assets/sf0.jpg";
import SF1 from "../assets/sf1.jpg";
import SF2 from "../assets/sf2.jpg";


export const FictionData = [
    {
        id: 1,
        name: "Paths of Darkness",
        image: LLARS0,
        skills: "Stack: ",
        amazon: "https://github.com/tfbielawski/netflix-clone",
        googlePlay: "https://netflix-clone-d1be7.web.app",
        kobo: "",
        barnes:null,
        description: `Prelude to the Chronicles of Llars`,
    },    
    {
        id: 2,
        name: "A Tide of Shadows",
        image: LLARS1,
        skills: "Stack: ",
        amazon: "https://github.com/tfbielawski/mern-auth-app",
        googlePlay: "https://mern-auth-app-gray.vercel.app",
        kobo:null,
        barnes:null,
        description: `The Chronicles of Llars: Volume I`,
    },
    {
        id: 3,
        name: "The Black Keep",
        image: LLARS2,
        skills: "Stack: ",
        amazon: "https://www.stepupforstudents.org",
        googlePlay: "https://www.stepupforstudents.org",
        kobo:null,
        barnes:null,
        description: `The Chronicles of Llars: Volume II`,
    },
    {
        id: 4,
        name: "Shadowblade",
        image: LLARS3,
        skills: "Stack: ",
        amazon: "https://www.acstechnologies.com/ministryplatform/tools/pocketplatform/",
        googlePlay: "https://www.acstechnologies.com/ministryplatform/tools/pocketplatform/",
        kobo:null,
        barnes:null,
        description: `The Chronicles of Llars: Volume III`,
    },
    {
        id: 5,
        name: "The Tomb of the Dark Paladin",
        image: LLARS4,
        skills: "Stack: ",
        amazon: "https://github.com/tfbielawski/nasa-apod-2",
        googlePlay: "https://nasa-apod-2.vercel.app",
        kobo:null,
        barnes:null,
        description: `The Chronicles of Llars: Volume IV`,
    },
    {
        id: 6,
        name: "The Crown of Power",
        image: LLARS5,
        skills: "Stack: ",
        amazon: "https://github.com/tfbielawski/new-reactdd-vercel",
        googlePlay: "https://new-reactdd-vercel.vercel.app",
        kobo:"",
        barnes:null,
        description: `The Chronicles of Llars: Volume V`,
    },
    {
        id: 7,
        name: "Rise of the GodSlayer",
        image: LLARS6,
        skills: "Stack: ",
        amazon: "https://github.com/tfbielawski/react-tac-toe-vercel",
        googlePlay: "https://react-tac-toe-vercel.vercel.app",
        kobo: "https://github.com/tfbielawski/mern-auth-app",
        barnes:null,
        description: `The Chronicles of Llars: Volume VI`,
    },
    {
        id: 8,
        name: "Godslayer",
        // image: LLARS7,
        skills: "Stack: ",
        amazon: null,
        googlePlay:null,
        kobo:null,
        barnes:null,
        description: `The final installment in the Chronicles of Llars. Coming in 2025`,
    },
    {
        id: 9,
        name: "The Centaurus Legacy",
        image: SF0,
        skills: "Stack: ",
        amazon: "https://github.com/tfbielawski/react-wx-vercel",
        googlePlay: "https://react-wx-vercel.vercel.app",
        kobo:null,
        barnes:null,
        description: `Heck Thomas sci-fi thriller trilogy, Volume 0`,
    },
    {
        id: 10,
        name: "The Orion Deception",
        image: SF1,
        skills: "Stack: ",
        amazon: "https://github.com/tfbielawski/netflix-clone",
        googlePlay: "https://react-essentials-lilac.vercel.app",
        kobo:null,
        barnes:null,
        description: `Heck Thomas sci-fi thriller trilogy, Volume I`,
    },
    {
        id: 11,
        name: "Rigel's Escape",
        image: SF2,
        skills: "Stack: ",
        amazon: "https://github.com/tfbielawski/project-management",
        googlePlay: "https://project-management-henna.vercel.app",
        kobo:null,
        barnes:null,
        description: `Heck Thomas sci-fi thriller trilogy, Volume II`,
    },
    {
        id: 12,
        name: "Heck Thomas",
        // image: LLARS7,
        skills: "Stack: ",
        amazon: null,
        googlePlay:null,
        kobo:null,
        barnes:null,
        description: `The final installment in the Heck Thomas trilogy. Coming in 2026`,
    },
    // {
    //     id: 12,
    //     name: "Destination Chooser",
    //     image: VAC,
    //     skills: "Stack: ",
    //     repo: "https://github.com/tfbielawski/destination-chooser",
    //     deploy: "https://destination-chooser-pied.vercel.app",
    //     description: `ReactJS, browser functions, local storage`,
    // },
    // {
    //     id: 13,
    //     name: "React Food App Full Stack",
    //     image: FOOD,
    //     skills: "Stack: ",
    //     repo: "https://github.com/tfbielawski/react-food-app",
    //     deploy: "https://react-food-app-rho.vercel.app",
    //     description: `ReactJS, NodeJS, Full Stack, Backend running on Render, Frontend on Vercel`,
    // },
    // {
    //     id: 13,
    //     name: "Quiz app",
    //     image: NETB3,
    //     skills: "Stack: ",
    //     repo: "https://github.com/tfbielawski/netflix-clone",
    //     deploy: "https://netflix-clone-d1be7.web.app",
    //     description: `Netflix clone webapp with login, auth, profile page, and current titles using TMDB api.`,
    // },
    // {
    //     id: 14,
    //     name: ".NET APP",
    //     image: NETB3,
    //     skills: "Stack: ",
    //     repo: "https://github.com/tfbielawski/netflix-clone",
    //     deploy: "https://netflix-clone-d1be7.web.app",
    //     description: `Netflix clone webapp with login, auth, profile page, and current titles using TMDB api.`,
    // },
]